version: "3.7"

services:
  app:
    build: .
    command: ["./wait-for-hub.sh", 'python -u ./bot-detector/main.py']
    depends_on:
      - hub

  hub:
    image: selenium/hub:3.141.59-krypton
    ports:
      - 4444:4444

  #
  # todo: need use swarm instead of this
  # https://github.com/SeleniumHQ/docker-selenium
  #
  browser:
    image: selenium/node-chrome:3.141.59-krypton
    shm_size: 256M
    logging:
      driver: none
    depends_on:
      - hub
    #    deploy:
    #      replicas: 2
    environment:
      NODE_MAX_INSTANCES: 5
      NODE_MAX_SESSION: 5
      # START_XVFB: 0
      HUB_HOST: hub
      HUB_PORT: 4444
    # entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'
